<?php
/**
 * Created by JetBrains PhpStorm.
 * User: maxit
 * Date: 8/20/13
 * Time: 7:02 PM
 * To change this template use File | Settings | File Templates.
 */

function kapasoft_config_menu(){
    $items = array();

    //Admin config group

    $items['admin/config/kapasoft'] = array(
        'title' => 'Kapasoft',
        'description' => 'Configure Interface with Driver',
        'access arguments' => array('administer kapasoft configurations'),
    );

    //admin configuraiton - settings
    $items['admin/config/kapasoft/manage'] = array(
        'title' => 'Kapasoft configuration',
        'description' => 'Manage Kapasoft Interface config settings',
        'access arguments' => array('administer kapasoft configurations'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('kapasoft_config_settings_form'),
    );

    return $items;
}


function kapasoft_config_settings_form($nodes, &$form_state){
    $form = array();

    $form['overview'] = array(
        '#markup' => t('This interface allows to manage KapaSoft modules Settings'),
        '#prefix' => '<p>',
        '#suffix' => '</p>',
    );

    $form['interface_config'] = array(
        '#title' => t('Interface Config'),
        '#description' => t('Configurations of Driver'),
        '#type' => 'fieldset',
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
    );

    $form['interface_config']['kapasoft_driver_url'] = array(
        '#title' => t('Driver Url'),
        '#description' => t('url of the driver'),
        '#type' => 'textfield',
        '#default_value' => variable_get('kapasoft_driver_url'),
        '#required' => TRUE,
    );

    $form['interface_config']['kapasoft_driver_port'] = array(
        '#title' => t('Driver Port'),
        '#description' => t('port of the driver'),
        '#type' => 'textfield',
        '#default_value' => variable_get('kapasoft_driver_port'),
        '#required' => TRUE,
    );

    return system_settings_form($form);
}

function kapasoft_config_settings_form_submit($form, &$form_state){
    //rebuild the form
    $form_state['rebuild'] = TRUE;

    variable_set('kapasoft_driver_url', $form_state['values']['driver_url']);
    variable_set('kapasoft_driver_port', $form_state['values']['driver_port']);

    //notify user
    drupal_set_message(t('kapasoft driver settings are saved'));
}


/*****Create Block********/
function kapasoft_config_block_info(){
    $blocks = array();

    $blocks['driver_configurations'] = array(
        'info' => t('KapaSoft: Driver Configurations'),//admin ui block name
        'cache' => DRUPAL_NO_CACHE,
    );
    $blocks['driver_configurations_bottom'] = array(
        'info' => t('KapaSoft: Driver Configurations Bottom'),//admin ui block name
        'cache' => DRUPAL_NO_CACHE,
    );
    return $blocks;
}

function kapasoft_config_block_view($delta = ''){
    $block = array();
    switch($delta){
        case 'driver_configurations':{
       $block['content'] = array(
                  '#markup' => driver_config_content($delta),
              );
            break;
            }
        case 'driver_configurations_bottom':{
            $block['content'] = array(
                '#markup' => driver_config_content($delta),
            );
            break;
        }

        }
    return $block;
}

function driver_config_content($delta){
    $drive_config = '';
    switch($delta){
        case 'driver_configurations':{
            $drive_config .= '<script>';
            $drive_config .=  'var MIN_CONFIG = (function () {';
            $drive_config .=  'var viewDriverHost = "'.variable_get('kapasoft_driver_url').'";';
            $drive_config .= 'var viewDriverPort = "'.variable_get('kapasoft_driver_port').'";';
            $drive_config .=  'return {';
            $drive_config .=  'getDriverUrl: function () {';
            $drive_config .=  "return 'http://' + viewDriverHost + ':' + viewDriverPort;";
            $drive_config .=  '}';
            $drive_config .=  '};';
            $drive_config .=  '}());';
            $drive_config .=  "var socket = ''";
            $drive_config .=  '</script>'."\n";
            break;
        }
        case 'driver_configurations_bottom':{
            $drive_config .=  '<script src="http://'.variable_get('kapasoft_driver_url').':'.variable_get('kapasoft_driver_port').'/socket.io/socket.io.js"></script>'."\n";
            $drive_config .=  "<script>jQuery( document ).ready(function($) {"."\n";
            $drive_config .=  "socket = io.connect(MIN_CONFIG.getDriverUrl(),{'connect timeout': 1000});"."\n";
            $drive_config .=  "});</script>"."\n";
            break;
        }
    }
    return $drive_config;
}